<?php

namespace Gigadrive\Bundle\SymfonyExtensionsBundle;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * Bundle
 *
 * @package Gigadrive\Bundle\SymfonyExtensionsBundle
 * @author Mehdi Baaboura <mbaaboura@gigadrivegroup.com>
 */
class GigadriveSymfonyExtensionsBundle extends Bundle {
	public function build(ContainerBuilder $container) {
		parent::build($container); // TODO: Change the autogenerated stub
	}
}