services:
    _defaults:
        autowire: true
        autoconfigure: true

    Gigadrive\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Constants,Entity,Migrations,Tests,Kernel.php,GigadriveSymfonyExtensionsBundle.php}'