services:
    _defaults:
        autowire: true
        autoconfigure: true

    Gigadrive\Bundle\SymfonyExtensionsBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Constants,Entity,Migrations,Tests,Kernel.php,GigadriveSymfonyExtensionsBundle.php}'