<?php
/**
 * Copyright (C) 2018-2020 Gigadrive - All rights reserved.
 * https://gigadrivegroup.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org/licenses/>
 */

namespace Gigadrive\Bundle\SymfonyExtensionsBundle;

use Gigadrive\Bundle\SymfonyExtensionsBundle\DependencyInjection\GigadriveSymfonyExtensionsExtension;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * Bundle
 *
 * @package Gigadrive\Bundle\SymfonyExtensionsBundle
 * @author Mehdi Baaboura <mbaaboura@gigadrivegroup.com>
 */
class GigadriveSymfonyExtensionsBundle extends Bundle {
	public function build(ContainerBuilder $container) {
		parent::build($container); // TODO: Change the autogenerated stub
	}

	public function getContainerExtension() {
		return new GigadriveSymfonyExtensionsExtension();
	}
}